[2025-03-31T21:34:08.493-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-31T21:34:08.497-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: employee_changes_report.upload_to_s3 scheduled__2025-03-01T00:00:00+00:00 [queued]>
[2025-03-31T21:34:08.500-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: employee_changes_report.upload_to_s3 scheduled__2025-03-01T00:00:00+00:00 [queued]>
[2025-03-31T21:34:08.500-0300] {taskinstance.py:2303} INFO - Starting attempt 5 of 6
[2025-03-31T21:34:08.505-0300] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): upload_to_s3> on 2025-03-01 00:00:00+00:00
[2025-03-31T21:34:08.508-0300] {standard_task_runner.py:63} INFO - Started process 12313 to run task
[2025-03-31T21:34:08.511-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'employee_changes_report', 'upload_to_s3', 'scheduled__2025-03-01T00:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/employee_changes_report_dag.py', '--cfg-path', '/var/folders/pw/ybzcyby54d787c124gv_5tjw0000gn/T/tmpekyqt6s0']
[2025-03-31T21:34:08.512-0300] {standard_task_runner.py:91} INFO - Job 23: Subtask upload_to_s3
[2025-03-31T21:34:08.528-0300] {task_command.py:426} INFO - Running <TaskInstance: employee_changes_report.upload_to_s3 scheduled__2025-03-01T00:00:00+00:00 [running]> on host ordenador-portatil-de-user-2.local
[2025-03-31T21:34:08.549-0300] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='employee_changes_report' AIRFLOW_CTX_TASK_ID='upload_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2025-03-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-01T00:00:00+00:00'
[2025-03-31T21:34:08.550-0300] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-31T21:34:08.732-0300] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-03-31T21:34:08.733-0300] {connection_wrapper.py:328} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from extra.
[2025-03-31T21:34:25.294-0300] {employee_changes_report_dag.py:126} INFO - Reporte subido exitosamente a S3: reports/employee_changes_20250331_213408.csv
[2025-03-31T21:34:25.298-0300] {python.py:237} INFO - Done. Returned value was: None
[2025-03-31T21:34:25.298-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-31T21:34:25.306-0300] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=employee_changes_report, task_id=upload_to_s3, execution_date=20250301T000000, start_date=20250401T003408, end_date=20250401T003425
[2025-03-31T21:34:25.352-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-03-31T21:34:25.381-0300] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-31T21:34:25.383-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
