[2025-04-01T00:31:52.749-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-01T00:31:52.756-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: employee_changes_report.upload_to_s3 manual__2025-04-01T03:30:29.097721+00:00 [queued]>
[2025-04-01T00:31:52.759-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: employee_changes_report.upload_to_s3 manual__2025-04-01T03:30:29.097721+00:00 [queued]>
[2025-04-01T00:31:52.759-0300] {taskinstance.py:2303} INFO - Starting attempt 1 of 3
[2025-04-01T00:31:52.764-0300] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): upload_to_s3> on 2025-04-01 03:30:29.097721+00:00
[2025-04-01T00:31:52.767-0300] {standard_task_runner.py:63} INFO - Started process 14133 to run task
[2025-04-01T00:31:52.770-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'employee_changes_report', 'upload_to_s3', 'manual__2025-04-01T03:30:29.097721+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/employee_changes_report_dag.py', '--cfg-path', '/var/folders/pw/ybzcyby54d787c124gv_5tjw0000gn/T/tmpnalyx6x0']
[2025-04-01T00:31:52.771-0300] {standard_task_runner.py:91} INFO - Job 30: Subtask upload_to_s3
[2025-04-01T00:31:52.785-0300] {task_command.py:426} INFO - Running <TaskInstance: employee_changes_report.upload_to_s3 manual__2025-04-01T03:30:29.097721+00:00 [running]> on host ordenador-portatil-de-user-2.local
[2025-04-01T00:31:52.807-0300] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='employee_changes_report' AIRFLOW_CTX_TASK_ID='upload_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2025-04-01T03:30:29.097721+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-01T03:30:29.097721+00:00'
[2025-04-01T00:31:52.808-0300] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-01T00:31:52.982-0300] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-04-01T00:31:52.982-0300] {connection_wrapper.py:328} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from extra.
[2025-04-01T00:32:09.285-0300] {employee_changes_report_dag.py:126} INFO - Reporte subido exitosamente a S3: reports/employee_changes_20250401_003152.csv
[2025-04-01T00:32:09.287-0300] {python.py:237} INFO - Done. Returned value was: None
[2025-04-01T00:32:09.288-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-01T00:32:09.294-0300] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=employee_changes_report, task_id=upload_to_s3, execution_date=20250401T033029, start_date=20250401T033152, end_date=20250401T033209
[2025-04-01T00:32:09.325-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-01T00:32:09.332-0300] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-01T00:32:09.333-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
